### ISSUE TITLE
How to create a new label file? 

### ISSUE THREAD

**Issue by zyqdragon** [sih4sing5hong5/hts_engine_python#7]
How to create a new label file?  So new voices can be synthesized. Is there any tutorial?

**Comment by sih4sing5hong5** [comment]
You can try the [Speaker dependent training demo ](http://hts.sp.nitech.ac.jp/?Download#s13a2a5e) provided by HTS.

**Comment by zyqdragon** [comment]
Thank you for your reply. But the Speaker dependent training demo can't provide chinese label. is there any project that can provide the corresponding chinese label?

**Comment by sih4sing5hong5** [comment]
The labels are generated by linguistic rules.
You can try modern end2end models like [WaveRNN](https://github.com/fatchord/WaveRNN), so that you don't need a lot of linguistic knowledge.
There is some open-source Taioanoe resource, provided by [ÌTHUÂN](https://ithuan.tw/%e5%85%a8%e9%83%a8%e5%b0%88%e6%a1%88), where I work for.

**Comment by zyqdragon** [comment]
I see. Thank you so much!
